# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('gender', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('nickname', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('ssn', models.CharField(max_length=11)),
                ('zipcode', models.CharField(max_length=5)),
                ('addr', models.TextField(max_length=45)),
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
